### ISSUE TITLE
EFI success?

### ISSUE THREAD

**Issue by akwangl** [qhuyduong/RedmiBook-Pro-15S-hackintosh#1]

**Comment by qhuyduong** [comment]
Yes. Almost everything is working. I'll update README soon.

**Comment by akwangl** [comment]
I've been having trouble solving XHC1 and XHC0, and can only turn off half the USB to work properly

**Comment by qhuyduong** [comment]
It's known issue. I'm turning off XHC1 too.
There has been attempts from NootedRed team to fix this. Just keep watching.

**Comment by akwangl** [comment]
Ok, I am redmibook pro 15, 21 models, CPU：AMD5600H.  Besides USB customization and core modification, can I directly reuse your EFI

**Comment by qhuyduong** [comment]
You can. You had better turn off XHC1 before hand, or it would not boot.

P/s: the EFI is for Monterey.

**Comment by akwangl** [comment]
I tried to shut down XHC1 and restore it to its original configuration.  However, the USB port on the left cannot be used.  In principle, all USB ports should work as before
