### ISSUE TITLE
Info show wrong

### ISSUE THREAD

**Issue by JL2048Go** [qhuyduong/RedmiBook-Pro-15S-hackintosh#10]
![PXL_20230704_140934739](https://github.com/qhuyduong/RedmiBook-Pro-15S-hackintosh/assets/36434553/78940ec5-9901-44b8-a1cc-e6f3b96de684)
I imported your config but found the graphics only have the size 512m.

**Comment by qhuyduong** [comment]
You have to increase the VRAM in BIOS settings.
