### ISSUE TITLE
Microphone problem

### ISSUE THREAD

**Issue by akwangl** [qhuyduong/RedmiBook-Pro-15S-hackintosh#2]
My sound card is Realtek ALC256, but the microphone doesn't work. Is your microphone working

**Comment by qhuyduong** [comment]
No. Microphone is not working for AMD atm, even desktops.
You'll have to wait.
Or give it a try on VoodooHDA. But the sound will be terrible.

**Comment by qhuyduong** [comment]
FYI microphone is now working 
https://github.com/qhuyduong/AMDMicrophone
