### ISSUE TITLE
Low-power patch   

### ISSUE THREAD

**Issue by akwangl** [qhuyduong/RedmiBook-Pro-15S-hackintosh#8]
![MKB0 DS~@P36R7IG1)AERSA](https://github.com/qhuyduong/RedmiBook-Pro-15S-hackintosh/assets/39325175/baea9d3c-f27a-4392-aa3f-1cb2df2de49f)

[NonMonotonicTimeWA.zip](https://github.com/qhuyduong/RedmiBook-Pro-15S-hackintosh/files/11720237/NonMonotonicTimeWA.zip)

**Comment by qhuyduong** [comment]
Interesting. How did you find it?

**Comment by akwangl** [comment]
@qhuyduong You'd better declare the NootedRed project in README.md. I saw in his telegram group that your project was blocked

**Comment by akwangl** [comment]
I found this in his telegram group

**Comment by qhuyduong** [comment]
>

> @qhuyduong You'd better declare the NootedRed project in README.md. I saw in his telegram group that your project was blocked

Already did
