### ISSUE TITLE
Shield usb controller xch1

### ISSUE THREAD

**Issue by akwangl** [qhuyduong/RedmiBook-Pro-15S-hackintosh#9]
[SSDT-RHUB.dsl.zip](https://github.com/qhuyduong/RedmiBook-Pro-15S-hackintosh/files/11723593/SSDT-RHUB.dsl.zip)

**Comment by qhuyduong** [comment]
Is it working?

**Comment by akwangl** [comment]
This is disabling xhc1 at the APCI level, which is better than BIOS, and at least windows is not affected by it

**Comment by qhuyduong** [comment]
@akwangl do you experience random freezes? Like the cursor can move but not being able to click anything.

**Comment by akwangl** [comment]
This happens to the trackpad @qhuyduong

**Comment by qhuyduong** [comment]
> This happens to the trackpad @qhuyduong 

I'm using external mouse so it's not trackpad issue. 

It looks like the freeze in the OS.

**Comment by akwangl** [comment]
You're still working on AMD?  I don't use it anymore.  I'm using windows now, and I wonder if it would be easier to change to catalina @qhuyduong

**Comment by akwangl** [comment]
Opencore 0.9.4 has many features, upgrade it
